services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ab_tests
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ab_tests"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cassandra:
    image: cassandra:4.1
    container_name: cassandra-db
    ports: ["9042:9042"]
    volumes: [cassandra_data:/var/lib/cassandra]
    environment:
      CASSANDRA_CLUSTER_NAME: TestCluster
      CASSANDRA_DC: dc1
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  mongo:
    image: mongo:7.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - mongo_data:/data/db

  etcd:
    image: bitnami/etcd:3.5
    container_name: etcd-db
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-db:2379
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - etcd_data:/bitnami/etcd

  tester:
    build: .
    container_name: go-tester
    depends_on:
      postgres:
        condition: service_healthy
      cassandra:
        condition: service_healthy
      mongo:
        condition: service_healthy
      etcd:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports: ["9090:9090"]
    volumes: ["./prometheus:/etc/prometheus"]
    command: ['--config.file=/etc/prometheus/prometheus.yml']
    depends_on: [tester]

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports: [ "3000:3000" ]
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on: [ prometheus ]

volumes:
  postgres_data:
  cassandra_data:
  mongo_data:
  etcd_data: