services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ab_tests
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: unless-stopped

  seed_go:
    container_name: seed_go
    build:
      context: .
      dockerfile: ./db_mysql_test/seed/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/config.yaml

  read_go:
    container_name: read_go
    build:
      context: .
      dockerfile: ./db_mysql_test/read/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/config.yaml
    ports:
      - "8081:8081"

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:
