services:
  ydb:
    image: ydbplatform/local-ydb:latest
    container_name: ydb-db
    ports:
      - "2135:2135"
      - "2136:2136" # Добавлен порт gRPC
      - "8765:8765"
    environment:
      - YDB_DEFAULT_LOG_LEVEL=INFO
      - GRPC_TLS_PORT=2135
      - GRPC_PORT=2136
      - MON_PORT=8765
#    healthcheck:
#      test: ["CMD", "/ydb", "-e", "grpc://localhost:2136", "--ca-file", "/ydb_certs/ca.pem", "scheme", "ls", "/local"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
    volumes:
      - ydb_data:/ydb_data
      - ydb_certs:/ydb_certs

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: unless-stopped

  seed_go:
    container_name: seed_go
    build:
      context: .
      dockerfile: ./db_ydb_test/seed/Dockerfile
    depends_on:
      ydb:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/config.yaml

  read_go:
    container_name: read_go
    build:
      context: .
      dockerfile: ./db_ydb_test/read/Dockerfile
    depends_on:
      ydb:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/config.yaml
    ports:
      - "8081:8081"

volumes:
  ydb_data:
  prometheus_data:
  grafana_data:
  ydb_certs: