version: '3.8'
services:
  mongo-db:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  seed_go:
    build:
      context: ./db_mongo_test/seed
      dockerfile: Dockerfile
    depends_on:
      - mongo-db
    network_mode: bridge
    environment:
      - CONFIG_PATH=/app/config.yaml
  read_go:
    build:
      context: ./db_mongo_test/read
      dockerfile: Dockerfile
    depends_on:
      - mongo-db
    network_mode: bridge
    environment:
      - CONFIG_PATH=/app/config.yaml
volumes:
  mongodata:
