version: '3.8'
services:
  etcd-db:
    image: quay.io/coreos/etcd:v3.5.0
    ports:
      - "2379:2379"
    volumes:
      - etcddata:/etcd-data
    environment:
      - ETCD_DATA_DIR=/etcd-data
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ENABLE_V2=true
  seed_go:
    build:
      context: .
      dockerfile: ./db_etcd_test/seed/Dockerfile
    depends_on:
      - etcd-db
    network_mode: bridge
    environment:
      - CONFIG_PATH=/app/config.yaml
  read_go:
    build:
      context: .
      dockerfile: ./db_etcd_test/read/Dockerfile
    depends_on:
      - etcd-db
    network_mode: bridge
    environment:
      - CONFIG_PATH=/app/config.yaml
volumes:
  etcddata:
