services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd-db
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_NAME=etcd0
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-db:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-db:2380
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd-db:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
    healthcheck:
      test: ["CMD", "etcdctl", "--endpoints=http://localhost:2379", "endpoint", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - etcd_data:/etcd-data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: unless-stopped

  seed_go:
    container_name: seed_go
    build:
      context: .
      dockerfile: ./db_etcd_test/seed/Dockerfile
    depends_on:
      etcd:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/config.yaml

  read_go:
    container_name: read_go
    build:
      context: .
      dockerfile: ./db_etcd_test/read/Dockerfile
    depends_on:
      etcd:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/config.yaml
    ports:
      - "8081:8081"

volumes:
  etcd_data:
  prometheus_data:
  grafana_data: